### ISSUE TITLE
Work with MDN

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/payment-request-info#4]
I'm worried about us maintaining this repo - specially the developer examples. We should be working with the MDN folks instead, as it's duplicating their work. They are in a better position than us to communicate with developers, and to maintain documentation.

cc @torgo @dontcallmedom

**Comment by marcoscaceres** [comment]
This in with regards to https://github.com/w3c/payment-request-info/wiki/CodeExamples

**Comment by dontcallmedom** [comment]
paging @chrisdavidmills - how should we proceed with that proposal from an MDN perspective?

@marcoscaceres has this been discussed / approved by the [task force](https://github.com/w3c/webpayments/wiki/Adoption2017)?

**Comment by chrisdavidmills** [comment]
Sounds good to me. I would do these two things:

1. Move the examples page to somewhere on MDN, probably as a child of https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API
2. Turn each one of the snippets into a working example, and put them into the MDN code examples repo, underneath https://github.com/mdn/dom-examples/. So for example, mdn/dom-examples/payment-request/feature-detect, etc.

I would be happy to do the first one, and could do so really quickly. I'd probably like some help putting the code examples together, although I could push them to the repo if you lioke. I only ask this because I'm still not very familiar with the web payments stuff, and am snowed under atm.

**Comment by poshaughnessy** [comment]
(Hi, I've been involved with our Web Payment efforts and I'm hoping to get more involved with MDN too, so) I'd be happy to help with 2 if I can? It seems like it should just be a case of turning them into full HTML pages for each one and testing they work OK? How about I make an initial effort at it (just under some test repo) for review - and once they looked OK they could be added under `mdn/dom-examples`?

**Comment by dontcallmedom** [comment]
my (absolutely uninformed) advice would be to start on a fork of https://github.com/mdn/dom-examples/ so that your work can easily be brought as a  pull request down the line - and thanks for the offer, I think that's a great way to move this forward

**Comment by ianbjacobs** [comment]
Hi all,
I had missed this thread completely; sorry about that. Now watching the repo.
I support moving the code examples to MDN. However, there are other resources that may not be as useful there, such as the FAQ. Is that your sense as well?

Ian

**Comment by chrisdavidmills** [comment]
Thanks @poshaughnessy / @dontcallmedom — sounds perfect.

So are we OK to move the examples page to MDN? I might even add some more explanation and turn it into a full Usage guide article.

@ianbjacobs we have a few FAQs on MDN, but don't commonly create them as a matter of course when documenting APIs. If it was thought useful, I wouldn't be against putting it on MDN.

**Comment by ianbjacobs** [comment]
I have not worked with content on MDN previously. How is the content maintained? Who has write access?
Thanks!
Ian

**Comment by poshaughnessy** [comment]
Good idea @dontcallmedom, I can fork [dom-examples](https://github.com/mdn/dom-examples/blob/master/README.md) and make a PR for review.

**Comment by chrisdavidmills** [comment]
@ianbjacobs we use GitHub accounts for login; anyone with an account can log in and edit pages. We have a system whereby we can subscribe and watch pages that we have responsibility over, and check all the edits made to the different sections of the site. But yeah, basically anyone can get involved.

**Comment by ianbjacobs** [comment]
@chrisdavidmills, thanks for the explanation. Is there a specific person who has volunteered to take responsibility for the payment request content? (e.g., you or @poshaughnessy)?

Ian

**Comment by chrisdavidmills** [comment]
I am happy to watch the pages (I already watch quite a lot of API reference trees). I've just subscribed to:

* https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API and its subpages
* All the interface reference pages linked to under https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API#Interfaces, and their subpages.

**Comment by ianbjacobs** [comment]
I've linked a new MDN account with my GitHub account and am watching the same resources. 

When you and @poshaughnessy feel the time is right, let me know and I will redirect
 https://github.com/w3c/payment-request-info/wiki/CodeExamples
to
 https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API

Thanks!!
Ian

**Comment by poshaughnessy** [comment]
Hi. I've turned each code sample into a self-contained example page. Here's where I'm upto, in my fork:

https://github.com/poshaughnessy/dom-examples/tree/web-payments/payment-request

I'd like to do some more testing next. In particular, I should try to test the two which involve a specific Payment Handler ('Recommend Payment App' and 'Pre-Authorize Transaction')... I hope to do that and be able to submit a PR for review soon. I thought I'd share this in the meantime though to a) Let you all know I'm working on it! and b) Check if it looks like it's on the right track? Is this sort of what you imagined @chrisdavidmills? Any feedback appreciated :)

**Comment by ianbjacobs** [comment]
@poshaughnessy, thank you! I will have a look (later) this week and send comments. 

Ian

**Comment by chrisdavidmills** [comment]
@poshaughnessy these look great; cheers. The only thing I'd say is that we should add links to the live examples to the readme once the changes are merged.

Then I can start getting the page itself transferred over.

**Comment by ianbjacobs** [comment]
[Adding @rsolomakhin for awareness and to see if he has any comments.]

@poshaughnessy, this looks great!

**Comment by rsolomakhin** [comment]
Moving to MDN is a-okay with me!

**Comment by poshaughnessy** [comment]
Sorry for the delay everyone - got sidetracked for a few days!

Just looking back at the examples that include a Payment Handler, particularly ['Recommend Payment App'](https://github.com/poshaughnessy/dom-examples/blob/web-payments/payment-request/recommend-payment-app.html)...

Having had [this conversation about the TommyPay Payment Handler not being maintained any more](https://github.com/tommythorsen/webpayments-demo/pull/4), it sounds best if we reference / include a different example instead?

How about your [AlicePay](https://github.com/rsolomakhin/rsolomakhin.github.io/tree/master/alicepay) or [BobPay](https://github.com/rsolomakhin/rsolomakhin.github.io/tree/master/bobpay) example, @rsolomakhin?

**Comment by rsolomakhin** [comment]
The most featureful example is [bobpay.xyz](https://github.com/madmath/payment-request-show/tree/master/bobpay/public/pay). I have [simpler examples](https://github.com/rsolomakhin/rsolomakhin.github.io/tree/master/pr/apps/) as well, but none of them use the `openWindow()` call, which really makes Payment Handler shine.

**Comment by poshaughnessy** [comment]
Thanks for your patience everyone. I have switched the Recommend Payment App demo from TommyPay to BobPay now. 

I have started the PR here: https://github.com/mdn/dom-examples/pull/16 

I have a few questions remaining that I have written up in the PR description there though. I wonder if @rsolomakhin or someone else familiar with Payment Handlers could please help to answer? :)

**Comment by rsolomakhin** [comment]
Answered inline. Thank you for updating the docs!

**Comment by chrisdavidmills** [comment]
This is wonderful, thanks @poshaughnessy @rsolomakhin ! I have merged the PR to add the demos and made a few changes to the readme files, and I've moved the codeexamples text over to MDN:

https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API/Using_the_Payment_Request_API

It is mostly the same, but I've added links to each of the demos in appropriate places, plus I've added a basic guide section:

https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API/Using_the_Payment_Request_API#The_basics_of_making_a_payment

So, @ianbjacobs can you handle the redirect? And @marcoscaceres can I get a tech review from you on the article?

Thanks again to everyone for helping to pull this together.

**Comment by ianbjacobs** [comment]
Thank you all very much! I have removed the content from our wiki [1] and left a pointer to MDN. 

We might move some of the remaining content from our wiki to other places, but for the time being, I'd like to propose to add a link from "See also" at the bottom of the MDN page to the Web Payments FAQ:
 https://github.com/w3c/payment-request-info/wiki/FAQ

Thank you,

Ian

[1] https://github.com/w3c/payment-request-info/wiki/CodeExamples

**Comment by chrisdavidmills** [comment]
@ianbjacobs added:

https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API#See_also

**Comment by ianbjacobs** [comment]
Thank you, @chrisdavidmills!

**Comment by marcoscaceres** [comment]
@chrisdavidmills, could you help me with subscribing to changes to: https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API

I wasn't able to figure out how to do it :(

**Comment by marcoscaceres** [comment]
Closing this, as changes were moved over 🎉

**Comment by chrisdavidmills** [comment]
@marcoscaceres on the top right of the UI, next to the gear icon button, you should see an eye icon button. The subscribe options are under the eye button. Can you see it?

**Comment by marcoscaceres** [comment]
Ah, got it! thank you @chrisdavidmills!
